#include "clf_mcmc.h"
char Lf_mean[200];
char Inverse_matrix[200];
char Wp_mean[200];
char Inverse_matrix_xi[200];
double  Halo_file_redshift[lf_file_number];
double  Xi_redshift[xi_file_number];
double  Xi_redshift_name[xi_file_number];
double  Start_mag;
double  Start_mag_xi[xi_file_number];
double  End_mag;
int Mag_min;
int Mag_min_xi[xi_file_number];
int Mag_min_xi_acc[xi_file_number+1];
int Mag_min_xi_all=0;
int Start_point;
struct subhalo *Halodata[lf_file_number];
double Volume;
double Volume_inv;
double *Distribution;
double *Gauss_distribution;
double *Mass_bin;
double *Redshift_bin;
double *Redshift_bin_add;
double *Distance_bin_add;
int Mass_size=0, Z_size=0;
int Z_size_add=0;
int Z_size_cut[lf_file_number+1];
int Gauss_number=0;
double *N_h,*N_s;
double *Xicc, *Xics, *Xisc, *Xiss;
double *Mass_left, *Mass_right, *Mass_mid;
int Xi_nbin=0;
int Rp_bin=0;
int Rpi_bin=0;
int Nwp=0;
char **File_corr;
int Start_point_xi;
int Perpendicular_min;
double *Perpendicular;
